# netlify.toml

[build]
  [build]
  command = "cd todo-task-manager && npm ci && npm run build"
  publish = "todo-task-manager/dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200